version: "3.9"

services:
  app:
    build:
      context: ./backups
      dockerfile: Dockerfile
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./dumps:/app/dumps
      - ./backups/config.json:/app/config.json
      - ./backups/cron.log:/app/cron.log
      - ./.env:/app/.env   
    depends_on:
      - db
    restart: unless-stopped

  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    shm_size: 512mb
    env_file:
      - .env
    volumes:
      - postgres_13_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  postgres_13_volume:
